# Model arguments
model_name_or_path: Qwen/Qwen2-VL-2B-Instruct
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: '/home/lix0i/Xiang/RS/R1-V/data/RL_DOTA_train/DOTA_train'
dataset_configs:
- all
preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: "no"
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
use_reentrant: false
hub_model_id: Qwen2-VL-2B-Instruct-SFT
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 4096
max_steps: -1
num_train_epochs: 2
output_dir: outputs/DOTA_Qwen2-VL-2B-SFT
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 4
# push_to_hub: true
report_to:
- wandb
# save_strategy: "no"
save_steps: 100 
save_total_limit: 3
seed: 42
warmup_ratio: 0.1